// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlKOmWwYPC-6XHKggBObjfsCpncLn030',
    appId: '1:1075890442267:web:821f6710c7a551da6c68be',
    messagingSenderId: '1075890442267',
    projectId: 'soccercracks-e3ab6',
    authDomain: 'soccercracks-e3ab6.firebaseapp.com',
    storageBucket: 'soccercracks-e3ab6.firebasestorage.app',
    measurementId: 'G-WXBSC39E8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDweYugQhJEqpugdclkv97ChjQXOqHCQfI',
    appId: '1:1075890442267:android:702bdc1c69c88cd76c68be',
    messagingSenderId: '1075890442267',
    projectId: 'soccercracks-e3ab6',
    storageBucket: 'soccercracks-e3ab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCwUPwgg6DEr6fYj6VZM5WobMGxpbCsk',
    appId: '1:1075890442267:ios:6d6eebafdb3981556c68be',
    messagingSenderId: '1075890442267',
    projectId: 'soccercracks-e3ab6',
    storageBucket: 'soccercracks-e3ab6.firebasestorage.app',
    iosClientId: '1075890442267-ofskau4oeog0v2sjohsi0anpa6graeno.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLCwUPwgg6DEr6fYj6VZM5WobMGxpbCsk',
    appId: '1:1075890442267:ios:6d6eebafdb3981556c68be',
    messagingSenderId: '1075890442267',
    projectId: 'soccercracks-e3ab6',
    storageBucket: 'soccercracks-e3ab6.firebasestorage.app',
    iosClientId: '1075890442267-ofskau4oeog0v2sjohsi0anpa6graeno.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKlKOmWwYPC-6XHKggBObjfsCpncLn030',
    appId: '1:1075890442267:web:87cc76e9b367d8c16c68be',
    messagingSenderId: '1075890442267',
    projectId: 'soccercracks-e3ab6',
    authDomain: 'soccercracks-e3ab6.firebaseapp.com',
    storageBucket: 'soccercracks-e3ab6.firebasestorage.app',
    measurementId: 'G-TMQ2F3MTJK',
  );
}